import "~/styles/globals.css";
import "@uploadthing/react/styles.css";
import { ClerkProvider} from '@clerk/nextjs'
import { Inter } from "next/font/google";
import { Topnav } from "./_components/Topnav";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <NextSSRPlugin 
      routerConfig={extractRouterConfig(ourFileRouter)}
      />
      <body className={`font-sans ${inter.variable} flex flex-col gap-4`}>
        <Topnav/>
        {children}</body>
    </html>
    </ClerkProvider>
  );
}
